### ISSUE TITLE
PDFs need to be linked to site POINT files too

### ISSUE THREAD

**Issue by lynnshirley** [ArchSite/archsite-web#2]
Apparently you were only instructed to link the PDFs with the polygon site files but the steering committee said they also need then linked to site POINTS>

**Comment by SimulatedBones** [comment]
Just FYI...

The Arch. Site. points were wired up for the PDF links around the time you made this request.

**Comment by hodgsonm** [comment]
Tommy:

I am tracing down the resolution of a potential issue related to
Archaeological Site Points and the .pdf site files.   On march 29 you
stated the information below.    Can you confirm how this relationship was
made?   Are you linking the "Site Number", the "SITEID" or *what key*
between the point features and PDF Filenames?

Note:  I had assumed you were using the SIte numbers or SiteIDs but
Karen/Tamara just notified me that the point feature layer never had an
attribute field for the SITEIDs.

Thanks,

- Michael


:

Just FYI...

The Arch. Site. points were wired up for the PDF links around the time you
made this request.

Please test and close this issue if you feel the arch. site points are
functioning as you need.

Thanks,
